title: enriquebarragan.me
author: Emmanuel Enrique Barragan

exclude:
  - README.md
  - LICENSE
  - LICENSE-content.md

include:
  - pages

timezone: America/Chicago

collections:
  things-i-made:
    output: true
    permalink: /things-i-made/:slug/
