title: personal page
author: Emmanuel Enrique Barragan

exclude:
  - README.md
  - LICENSE
  - LICENSE-content.md

include:
  - pages

timezone: America/Chicago

collections:
  cards:
    output: true
    permalink: /cards/:slug/